### ISSUE TITLE
Site with LOTS of variables is very slow to load

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#30]
This is admittedly on Stroud's very slow internet, and far more variables than any normal site would have, but http://data.envirodiy.org/sites/28/ seems to take quite a while to load up for me.

**Comment by horsburgh** [comment]
OK - fair enough. Before we invest in optimization, can we settle on what our design use case is for the number of sensors that should load in a reasonable amount of time?  I think it would be something way less than 50.  It's slow because the sparkline plots are generated on the fly when the page loads.

**Comment by SRGDamia1** [comment]
@aufdenkampe ?  I imagine most of our users are going to be using no more than 10 variables and none of them with 12 significant figures.

**Comment by horsburgh** [comment]
As part of our efforts to better support larger numbers of sites and sites with large numbers of variables and data values we are testing a new, Linux based deployment environment to replace our current deployment on Windows. We are also considering a service to provide the most recent data values so that the generation of the sparkline plots can be separated from the page load for sites with many variables (i.e., so the page can load while the sparklines are being generated and then the  sparklines appear when they are ready - rather than waiting for up to 10 seconds for the page to load).

**Comment by horsburgh** [comment]
@SRGDamia1 - we've done a few things to address this issue. 

1. We are now running in a Linux environment using PostgreSQL on the back end for our production environment. I think that has helped some.
2. We have changed the way we are getting the data to display the sparkline plots and to preload the tabular views of the data. 

Pages for sites that were taking 20+ seconds to load for me earlier are now loading much more quickly.  For a site with 8 variables, it takes just a couple of seconds for the page to load on my home WIFI network (e.g., see http://data.envirodiy.org/sites/12/). 

do you have any sites you can check quickly to see if we can close this issue?

**Comment by jcaraballo17** [comment]
@horsburgh I've been on this for the past few days now because there are still a lot of performance issues coming from different places. I solved the slowest loading time by not loading the data values in the back-end, but doing it in a csv file, which reduced the time exponentially for results with a lot of values. Right now the loading time increases the more results a site has, and the site starts lagging when adding all the data (in some cases about 17,000 data values per result) to the table.

**Comment by horsburgh** [comment]
@jcaraballo17 - performance seems to be much improved for this. I think we've done enough here to close this issue when all of your enhancements have been pushed to production.

**Comment by aufdenkampe** [comment]
Nice work. It's all working much faster for me too!
