### ISSUE TITLE
Have better vertical axis in sparkline plots

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#44]
Provide some sort of label and standardized scaling for the vertical axis on the spark line plots including axis ticks.

**Comment by horsburgh** [comment]
@SRGDamia1 - sparkline plots, by definition, do not typically have axes or coordinates. They are designed to give an indication of the general shape of the variation in some measurement, usually over time. I think we are asking the sparklines to do too much because we don't have visualization capabilities added to the system yet.

**Comment by horsburgh** [comment]
@SRGDamia1 - for the moment, we are not going to change anything to address this issue. When @Maurier implements the standard 72 hour window for sparklines and we have the TSA implemented, we can reassess. I will leave this issue open and assign it to the next milestone for now, but it may get closed at that point.

**Comment by Elijahwalkerwest** [comment]
Deployed and ready for testing.

**Comment by horsburgh** [comment]
Closing this issue. Dynamic visualizations will be done by WebTSA.
