### ISSUE TITLE
Change heading for each Result

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2WebSDL#70]
@aufdenkampe , I'm not quite sure what you think the new names should be.

**Comment by SRGDamia1** [comment]
Include the "medium" in the variable title

**Comment by aufdenkampe** [comment]
We discussed prioritizing this in our 2017-08-10 EnviroDIY Data Portal call. 
This issue combines the need to rename the sensor Make_Model_Variable label (see issue #71), with a need for a better heading for each result, which currently looks like this:

**Variable** (Make_Model_Variable)

My Idea is that we at least add "Medium" to the Result heading, so that it's possible to distinguish between, for example, the four different Temperature results from http://data.envirodiy.org/sites/6/. Also, we should probably add Depth offsets too, once those are added.  This might be a good pattern.

**Medium-Variable** (Make_Model_Variable), X m deep.

**Comment by horsburgh** [comment]
@aufdenkampe - I would prefer to be a bit more explicit about how we display this information so that it is not ambiguous. I think we should do the following in the header of each Sparkline:

Variable: <Variable Name>(<Make_Model_VariableCode>)
Medium: <SampledMedium>

Let's deal with the Offset in #75.

**Comment by aufdenkampe** [comment]
@horsburgh, an explicit approach makes sense to me. I'm worried that <Make_Model_VariableCode>, however, is not easy to read as a heading.  How about this:

Medium: <SampledMedium>
Variable: <VariableName>
Sensor: <Make_Model>

Also, for the Citizen Science crowd, can we perhaps use a synonym for "Liquid aqueous" and call it "Liquid Water"?

**Comment by horsburgh** [comment]
I think this one looks good. Can close when deployed to production.

**Comment by aufdenkampe** [comment]
Looks awesome!
